---
title: "Introduccion a visualizaciones interactivas con R y fútbol"
subtitle: "Ciencia de Datos y Fútbol"
author: "Ramiro Fernández"
output: 
  html_document:
    df_print: paged
    fig_height: 8
    fig_width: 12
    #code_folding: "hide"
    toc: true
    toc_float:
      toc_collapsed: true
    toc_depth: 3
    number_sections: true
    theme: paper
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}


library(tidyverse)

jugadores <- read_csv('https://raw.githubusercontent.com/martoalalu/futbol-data-science/master/data/jugadores_superliga.csv')

unique(jugadores$player)

sand <- jugadores %>% filter(player=="J. Sand") %>% mutate(prop_acciones_exitosas=sum(total_actions_successful)/sum(total_actions)*100,                                                   prop_tiros_arco=sum(shots_on_target)/sum(total_shots)*100,
acierto_pase=sum(passes_accurate)/sum(total_passes)*100,
prop_duels_won=sum(duels_won)/sum(total_duels)*100,
prop_def_duels_won=sum(defensive_duels_won)/sum(total_defensive_duels)*100,
prop_att_duels_won=sum(offensive_duels_won)/sum(total_offensive_duels)*100)


sand <- sand[1,c('prop_acciones_exitosas', 'prop_tiros_arco', 'acierto_pase', 'prop_duels_won', 'prop_def_duels_won', 'prop_att_duels_won')]


abila <- jugadores %>% filter(player=="R. Ábila") %>% mutate(prop_acciones_exitosas=sum(total_actions_successful)/sum(total_actions)*100,                                                   prop_tiros_arco=sum(shots_on_target)/sum(total_shots)*100,
acierto_pase=sum(passes_accurate)/sum(total_passes)*100,
prop_duels_won=sum(duels_won)/sum(total_duels)*100,
prop_def_duels_won=sum(defensive_duels_won)/sum(total_defensive_duels)*100,
prop_att_duels_won=sum(offensive_duels_won)/sum(total_offensive_duels)*100)

abila <- abila[1,c('prop_acciones_exitosas', 'prop_tiros_arco', 'acierto_pase', 'prop_duels_won', 'prop_def_duels_won', 'prop_att_duels_won')]

data <- rbind(sand, abila)
data

row.names(data) <- c('José Sand', 'Ramon Ábila')
data <- as.matrix(data)

#Guardo mis nombres de atributos y su extensión
Attributes = colnames(data)
AttNo = length(Attributes)

#Genero mi data con un valor final igual para asegurar el círculo
data <- cbind(data, data[,1])

#Seteo el marco con ggplot
ggplot() + xlim(c(-120, 120)) + ylim(c(-120, 150))

#Genero una función que me traiga el círculo
circleFun <- function(center = c(0,0),diameter = 1, npoints = 100){
    r = diameter / 2
    tt <- seq(0,2*pi,length.out = npoints)
    xx <- center[1] + r * cos(tt)
    yy <- center[2] + r * sin(tt)
    return(data.frame(x = xx, y = yy))
}

#Genero los círculos que van a dar el radar
circle1 <- circleFun(c(0,0),200,npoints = 100)
circle2 <- circleFun(c(0,0),150,npoints = 100)
circle3 <- circleFun(c(0,0),100,npoints = 100)
circle4 <- circleFun(c(0,0),50,npoints = 100)

## Agrego el background del radar
ggplot() + xlim(c(-120, 120)) + ylim(c(-120, 150)) + 
## Agrego los círculos
geom_polygon(data = circle1, aes(x=x,y=y),fill = "#F0F0F0", colour = "#969696") + geom_polygon(data = circle2, aes(x=x,y=y),fill = "#FFFFFF", colour = "#d9d9d9") + geom_polygon(data = circle3, aes(x=x,y=y),fill = "#F0F0F0", colour = "#d9d9d9") + geom_polygon(data = circle4, aes(x=x,y=y),fill = "#FFFFFF", colour = "#d9d9d9")


## Agrego el background
ggplot() + xlim(c(-120, 120)) + ylim(c(-120, 150)) + 
## Agrego los círculos
geom_polygon(data = circle1, aes(x=x,y=y),fill = "#F0F0F0", colour = "#969696") + geom_polygon(data = circle2, aes(x=x,y=y),fill = "#FFFFFF", colour = "#d9d9d9") + geom_polygon(data = circle3, aes(x=x,y=y),fill = "#F0F0F0", colour = "#d9d9d9") + geom_polygon(data = circle4, aes(x=x,y=y),fill = "#FFFFFF", colour = "#d9d9d9") +
## Agrego un fondo removiendo el predeterminado por ggplot
theme_void()


angle_spilt <- (2*pi) / (AttNo)
angle_spilt_seq <- seq(0,(2*pi),angle_spilt)
angle_spilt_seq


# Genero dataframes vacíos para albergar mis variables
LineData <- data.frame(x=NA, y=NA, stringsAsFactors = F)
TitlePositioning <- data.frame(title=NA, x=NA, y=NA, stringsAsFactors = F)

## Creo el background donde voy a construir los datos con un for loop 
for (i in 1:NCOL(data)) {
  angle_multiplier <- if(i < NCOL(data)){i}else{1}
  radians_for_segment <- angle_spilt_seq[i]

  x <- 100 * cos(radians_for_segment)
  y <- 100 * sin(radians_for_segment)
  temp <- data.frame(x = x, y = y, stringsAsFactors = F)
  LineData <- rbind(temp, LineData)
  
  x <- 112 * cos(radians_for_segment)
  y <- 112 * sin(radians_for_segment)
  title <- colnames(data)[i]
  temp <- data.frame(title = title, x = x, y = y, stringsAsFactors = F)
  TitlePositioning <- rbind(temp, TitlePositioning)
}

## Creo las etiquetas de mis datos
values <- c(25,50,75)
radian_for_values <- angle_spilt / 2
x <- values * cos(radian_for_values)
y <- values * sin(radian_for_values)
ValuePositioning <- data.frame(values = values, x = x, y = y, stringsAsFactors = F)

## Agrego valores de origen para las líneas 
LineData$x2 <- 0
LineData$y2 <- 0

## Chequeo la data
LineData
TitlePositioning
ValuePositioning


## Agrego el background
ggplot() + xlim(c(-120, 120)) + ylim(c(-120, 150)) + 
## Agrego los círculos
geom_polygon(data = circle1, aes(x=x,y=y),fill = "#F0F0F0", colour = "#969696") + geom_polygon(data = circle2, aes(x=x,y=y),fill = "#FFFFFF", colour = "#d9d9d9") + geom_polygon(data = circle3, aes(x=x,y=y),fill = "#F0F0F0", colour = "#d9d9d9") + geom_polygon(data = circle4, aes(x=x,y=y),fill = "#FFFFFF", colour = "#d9d9d9") +
## Saco el fondo
theme_void() +
## Agrego líneas y los nombres de los atributos
geom_segment(data=LineData, aes(x = LineData$x, y = LineData$y, xend = LineData$x2, yend = LineData$y2),colour = "#d9d9d9", linetype = "dashed") + 
annotate("text", x = TitlePositioning$x , y = TitlePositioning$y, label = TitlePositioning$title, size= 2.5) +  
annotate("text", x = ValuePositioning$x , y = ValuePositioning$y, label = ValuePositioning$values, size= 2.5, colour = "#969696")



# Genero un dataframe vacío para albergar la data
polydata <- data.frame(player=NA, value=NA, radians=NA, x=NA, y=NA, stringsAsFactors = F)

## Creo el polígono para los datos de mis jugadores
for (i in 1:NCOL(data)) {
  
  for (p in 1:NROW(data)) {
    
  player2calc <- data[p,]
  angle_multiplier <- if(i < NCOL(data)){i}else{1}
  radians_for_segment <- angle_spilt_seq[i]
  x <- player2calc[i] * cos(radians_for_segment)
  y <- player2calc[i] * sin(radians_for_segment)
  player <- rownames(data)[p]
  temp <- data.frame(player = player, value = player2calc[i], radians = radians_for_segment, x = x, y = y, stringsAsFactors = F)
  polydata <- rbind(temp, polydata)
  }
}
head(polydata)

## Separo la data entre jugador 1 y jugador 2
playersDB <- unique(polydata$player)
player1 <- polydata[(polydata$player == playersDB[1]),]
player2 <- polydata[(polydata$player == playersDB[2]),]

## Agrego el background visual
ggplot() + xlim(c(-120, 120)) + ylim(c(-120, 150)) + 
## Agrego círculos
geom_polygon(data = circle1, aes(x=x,y=y),fill = "#F0F0F0", colour = "#969696") + geom_polygon(data = circle2, aes(x=x,y=y),fill = "#FFFFFF", colour = "#d9d9d9") + geom_polygon(data = circle3, aes(x=x,y=y),fill = "#F0F0F0", colour = "#d9d9d9") + geom_polygon(data = circle4, aes(x=x,y=y),fill = "#FFFFFF", colour = "#d9d9d9") +
## Cambio el tema a vacío (remuevo el default)
theme_void() +
## Agrego los segmentos de líneas y los títulos de atributos y valores 
geom_segment(data=LineData, aes(x = LineData$x, y = LineData$y, xend = LineData$x2, yend = LineData$y2),colour = "#d9d9d9", linetype = "dashed") + 
annotate("text", x = TitlePositioning$x , y = TitlePositioning$y, label = TitlePositioning$title, size= 2.5) +  
annotate("text", x = ValuePositioning$x , y = ValuePositioning$y, label = ValuePositioning$values, size= 2.5, colour = "#969696") +
## Agrego la data del jugador 1
geom_polygon(data = player1, aes(x=x,y=y),fill = "#A30845", colour = "#A30845", alpha = 0.3) + geom_point(data = player1, aes(x = x, y = y),size=0.3, colour= "#A30845")


## Croe el string para el jugador 1
Player1_title <- gsub('([[:upper:]])', ' \\1', playersDB[1])
Player1_title <- trimws(Player1_title)

## Agrego el background
ggplot() + xlim(c(-120, 120)) + ylim(c(-120, 150)) + 
## Agrego círculos
geom_polygon(data = circle1, aes(x=x,y=y),fill = "#F0F0F0", colour = "#969696") + geom_polygon(data = circle2, aes(x=x,y=y),fill = "#FFFFFF", colour = "#d9d9d9") + geom_polygon(data = circle3, aes(x=x,y=y),fill = "#F0F0F0", colour = "#d9d9d9") + geom_polygon(data = circle4, aes(x=x,y=y),fill = "#FFFFFF", colour = "#d9d9d9") +
## Cambio el tema a vacío (remuevo el default)
theme_void() +
## Agrego los segmentos de líneas y los títulos de atributos y valores 
geom_segment(data=LineData, aes(x = LineData$x, y = LineData$y, xend = LineData$x2, yend = LineData$y2),colour = "#d9d9d9", linetype = "dashed") + 
annotate("text", x = TitlePositioning$x , y = TitlePositioning$y, label = TitlePositioning$title, size= 2.5) +  
annotate("text", x = ValuePositioning$x , y = ValuePositioning$y, label = ValuePositioning$values, size= 2.5, colour = "#969696") +
## Agrego la data del jugador 1
geom_polygon(data = player1, aes(x=x,y=y),fill = "#A30845", colour = "#A30845", alpha = 0.3) + geom_point(data = player1, aes(x = x, y = y),size=0.3, colour= "#A30845") + 
## Agrego título
annotate("text", x = -110 , y = 130, label = Player1_title, size= 5, colour = "#A30845", family = "Helvetica", fontface = "bold", hjust = 0) + 
annotate("text", x = 110 , y = 130, label = "Superliga Argentina Data", size= 4, colour = "#969696", family = "Helvetica", fontface = "bold", hjust = 1)


## Creo string de título para el jugador 2
Player2_title <- gsub('([[:upper:]])', ' \\1', playersDB[2])
Player2_title <- trimws(Player2_title)

## Agrego el background
p <- ggplot() + xlim(c(-120, 120)) + ylim(c(-120, 150)) + 
## Agrego círculos
geom_polygon(data = circle1, aes(x=x,y=y),fill = "#F0F0F0", colour = "#969696") + geom_polygon(data = circle2, aes(x=x,y=y),fill = "#FFFFFF", colour = "#d9d9d9") + geom_polygon(data = circle3, aes(x=x,y=y),fill = "#F0F0F0", colour = "#d9d9d9") + geom_polygon(data = circle4, aes(x=x,y=y),fill = "#FFFFFF", colour = "#d9d9d9") +
## Cambio el tema a vacío (remuevo el default)
theme_void() +
## Agrego los segmentos de líneas y los títulos de atributos y valores 
geom_segment(data=LineData, aes(x = LineData$x, y = LineData$y, xend = LineData$x2, yend = LineData$y2),colour = "#d9d9d9", linetype = "dashed") + 
annotate("text", x = TitlePositioning$x , y = TitlePositioning$y, label = TitlePositioning$title, size= 2.5) +  
annotate("text", x = ValuePositioning$x , y = ValuePositioning$y, label = ValuePositioning$values, size= 2.5, colour = "#969696") +
## Agrego la data del jugador 1
geom_polygon(data = player1, aes(x=x,y=y),fill = "#A30845", colour = "#A30845", alpha = 0.3) + geom_point(data = player1, aes(x = x, y = y),size=0.3, colour= "#A30845") + 
## Agrego título
annotate("text", x = -110 , y = 130, label = Player1_title, size= 5, colour = "#A30845", family = "Helvetica", fontface = "bold", hjust = 0) + 
annotate("text", x = 110 , y = 130, label = "Superliga Argentina Data", size= 4, colour = "#969696", family = "Helvetica", fontface = "bold", hjust = 1) +
## Agrego la data del jugador 2
geom_polygon(data = player2, aes(x=x,y=y),fill = "#00B20B", colour = "#00B20B", alpha = 0.3) +
geom_point(data = player2, aes(x = x, y = y),size=0.3, colour= "#00B20B") +
## Agrego títulos de jugador 2
annotate("text", x = -110 , y = 116, label = Player2_title, size= 5, colour = "#00B20B", family = "Helvetica", fontface = "bold", hjust = 0) + 
annotate("text", x = -110 , y = 123 , label = "vrs", size= 3, colour = "#969696", family = "Helvetica", hjust = 0)

p

library(plotly)

ggplotly(p)

```






